import { ProjectItem } from './types';

export const PORTFOLIO_DATA: {
  flyers: ProjectItem[];
  logos: ProjectItem[];
  social: ProjectItem[];
  books: ProjectItem[];
} = {
  flyers: [
    { id: 'flyer-1',  title: 'Glorious Sunday',               imageUrl: 'https://res.cloudinary.com/dxzw0j1tf/image/upload/v1776854937/flyer-1_n2tw24.jpg',  category: 'flyer', description: 'Church service promo flyer.' },
    { id: 'flyer-2',  title: 'Identity Immersion Series I',   imageUrl: 'https://res.cloudinary.com/dxzw0j1tf/image/upload/v1776854927/flyer-2_x2ch2m.jpg',  category: 'flyer', description: 'Immersion series event flyer.' },
    { id: 'flyer-3',  title: 'Identity Immersion Series II',  imageUrl: 'https://res.cloudinary.com/dxzw0j1tf/image/upload/v1776854919/flyer-3_g3t00s.jpg',  category: 'flyer', description: 'Immersion series event flyer.' },
    { id: 'flyer-4',  title: 'Battle 2',                      imageUrl: 'https://res.cloudinary.com/dxzw0j1tf/image/upload/v1776854882/flyer-4_frkd4a.jpg',  category: 'flyer', description: 'Spiritual warfare event flyer.' },
    { id: 'flyer-5',  title: 'Over Flow',                     imageUrl: 'https://res.cloudinary.com/dxzw0j1tf/image/upload/v1776854883/flyer-5_xwsovi.jpg',  category: 'flyer', description: 'Church overflow event flyer.' },
    { id: 'flyer-6',  title: 'Teaching & Fire Service',       imageUrl: 'https://res.cloudinary.com/dxzw0j1tf/image/upload/v1776854894/flyer-6_y9ucyt.jpg',  category: 'flyer', description: 'Fire service event flyer.' },
    { id: 'flyer-7',  title: 'Cross Over 2025',               imageUrl: 'https://res.cloudinary.com/dxzw0j1tf/image/upload/v1776854888/flyer-7_bqrwpr.jpg',  category: 'flyer', description: 'Crossover night service flyer.' },
    { id: 'flyer-8',  title: 'January Immersion 2025',        imageUrl: 'https://res.cloudinary.com/dxzw0j1tf/image/upload/v1776854900/flyer-8_trlgkz.jpg',  category: 'flyer', description: 'January immersion event flyer.' },
    { id: 'flyer-9',  title: 'December Immersion',            imageUrl: 'https://res.cloudinary.com/dxzw0j1tf/image/upload/v1776854892/flyer-9_aad6m1.jpg',  category: 'flyer', description: 'December immersion event flyer.' },
    { id: 'flyer-10', title: 'Faith & Healing Immersion',     imageUrl: 'https://res.cloudinary.com/dxzw0j1tf/image/upload/v1776854899/flyer-10_a0ekdv.jpg', category: 'flyer', description: 'Faith & healing programme flyer.' },
    { id: 'flyer-11', title: 'Front Immersion Righteousness', imageUrl: 'https://res.cloudinary.com/dxzw0j1tf/image/upload/v1776854902/flyer-11_aqolvf.jpg', category: 'flyer', description: 'Righteousness immersion flyer.' },
    { id: 'flyer-12', title: 'July Edition Refix',            imageUrl: 'https://res.cloudinary.com/dxzw0j1tf/image/upload/v1776854903/flyer-12_n1fvrr.jpg', category: 'flyer', description: 'July edition series flyer.' },
    { id: 'flyer-13', title: 'July Immersion',                imageUrl: 'https://res.cloudinary.com/dxzw0j1tf/image/upload/v1776854905/flyer-13_c2ytkk.jpg', category: 'flyer', description: 'July immersion programme flyer.' },
    { id: 'flyer-14', title: 'Soulathon',                     imageUrl: 'https://res.cloudinary.com/dxzw0j1tf/image/upload/v1776854906/flyer-14_hioh3h.jpg', category: 'flyer', description: 'Soulathon outreach event flyer.' },
    { id: 'flyer-15', title: 'Tetelestai ECM',                imageUrl: 'https://res.cloudinary.com/dxzw0j1tf/image/upload/v1776854930/flyer-15_ftlkjm.jpg', category: 'flyer', description: 'ECM Tetelestai conference flyer.' },
    { id: 'flyer-16', title: 'Wield the Sword 2025',          imageUrl: 'https://res.cloudinary.com/dxzw0j1tf/image/upload/v1776854913/flyer-16_eu41ag.jpg', category: 'flyer', description: 'Spiritual warfare series flyer.' },
    { id: 'flyer-17', title: 'Blessing',                      imageUrl: 'https://res.cloudinary.com/dxzw0j1tf/image/upload/v1776854920/flyer-17_y8o7e4.jpg', category: 'flyer', description: 'Blessing service event flyer.' },
    { id: 'flyer-18', title: 'Proverbs 31 Woman',             imageUrl: 'https://res.cloudinary.com/dxzw0j1tf/image/upload/v1776854918/flyer-18_p2nn1z.jpg', category: 'flyer', description: 'Women\'s conference flyer.' },
    { id: 'flyer-19', title: 'Mama 1',                        imageUrl: 'https://res.cloudinary.com/dxzw0j1tf/image/upload/v1776854929/flyer-19_lbcfta.jpg', category: 'flyer', description: 'Mothers day service flyer.' },
    { id: 'flyer-20', title: 'Certificate',                   imageUrl: 'https://res.cloudinary.com/dxzw0j1tf/image/upload/v1776854927/flyer-20_psnnrj.jpg', category: 'flyer', description: 'Church certificate design.' },
  ],

  logos: [
    { id: 'logo-1',  title: '0965 Foods – Logo Gold',        imageUrl: 'https://res.cloudinary.com/dxzw0j1tf/image/upload/v1776853371/logo-1_iogfax.jpg',  category: 'logo', description: 'Premium food brand logo in gold.' },
    { id: 'logo-2',  title: '0965 Foods – Business Card',    imageUrl: 'https://res.cloudinary.com/dxzw0j1tf/image/upload/v1776853401/logo-2_iq09e0.jpg',  category: 'logo', description: 'Business card design for 0965 Foods.' },
    { id: 'logo-3',  title: '0965 Foods – Cup Packaging',    imageUrl: 'https://res.cloudinary.com/dxzw0j1tf/image/upload/v1776853489/logo-3_bnebce.jpg',  category: 'logo', description: 'Branded packaging cup design.' },
    { id: 'logo-4',  title: '0965 Foods – Bag Branding',     imageUrl: 'https://res.cloudinary.com/dxzw0j1tf/image/upload/v1776853415/logo-4_kyzyup.jpg',  category: 'logo', description: 'Branded bag design.' },
    { id: 'logo-5',  title: 'Ibile Plus – Logo',             imageUrl: 'https://res.cloudinary.com/dxzw0j1tf/image/upload/v1776853395/logo-5_zg7mah.jpg',  category: 'logo', description: 'Logo design for Ibile Plus brand.' },
    { id: 'logo-6',  title: 'Ibile Plus – Business Card',    imageUrl: 'https://res.cloudinary.com/dxzw0j1tf/image/upload/v1776853363/logo-6_mcrgzl.jpg',  category: 'logo', description: 'Business card for Ibile Plus.' },
    { id: 'logo-7',  title: 'Inspirizu Tech – Logo',         imageUrl: 'https://res.cloudinary.com/dxzw0j1tf/image/upload/v1776853360/logo-7_ytmkzw.jpg',  category: 'logo', description: 'Tech startup logo design.' },
    { id: 'logo-8',  title: 'Inspirizu Tech – Stationery',   imageUrl: 'https://res.cloudinary.com/dxzw0j1tf/image/upload/v1776853439/logo-8_s6imed.jpg',  category: 'logo', description: 'Full stationery brand design.' },
    { id: 'logo-9',  title: 'Lilky Studios – Logo',          imageUrl: 'https://res.cloudinary.com/dxzw0j1tf/image/upload/v1776853361/logo-9_g52vz6.jpg',  category: 'logo', description: 'Studio brand logo design.' },
    { id: 'logo-12', title: 'Smoky Sips – Logo File 1',      imageUrl: 'https://res.cloudinary.com/dxzw0j1tf/image/upload/v1776853367/logo-12_y5hd0o.jpg', category: 'logo', description: 'Smoky Sips brand logo.' },
    { id: 'logo-13', title: 'Smoky Sips – Logo File 2',      imageUrl: 'https://res.cloudinary.com/dxzw0j1tf/image/upload/v1776853368/logo-13_hk9axi.jpg', category: 'logo', description: 'Logo variant for Smoky Sips.' },
    { id: 'logo-14', title: 'Smoky Sips – Logo File 3',      imageUrl: 'https://res.cloudinary.com/dxzw0j1tf/image/upload/v1776853387/logo-14_icyn5j.jpg', category: 'logo', description: 'Alternate logo for Smoky Sips.' },
    { id: 'logo-15', title: 'Premium Hair Gallery – Logo A',  imageUrl: 'https://res.cloudinary.com/dxzw0j1tf/image/upload/v1776853368/logo-15_usviqy.jpg', category: 'logo', description: 'Hair gallery primary logo.' },
    { id: 'logo-16', title: 'Premium Hair Gallery – Logo B',  imageUrl: 'https://res.cloudinary.com/dxzw0j1tf/image/upload/v1776853369/logo-16_r9alxw.jpg', category: 'logo', description: 'Alternate hair gallery logo.' },
    { id: 'logo-17', title: 'Premium Hair Gallery – Hoodie',  imageUrl: 'https://res.cloudinary.com/dxzw0j1tf/image/upload/v1776853407/logo-17_pxxnwi.jpg', category: 'logo', description: 'Branded merchandise design.' },
    { id: 'logo-18', title: 'Premium Hair Gallery – Hang Tag', imageUrl: 'https://res.cloudinary.com/dxzw0j1tf/image/upload/v1776853441/logo-18_hmjawu.jpg', category: 'logo', description: 'Product hang tag design.' },
    { id: 'logo-19', title: 'Premium Hair Gallery – Thank You Card', imageUrl: 'https://res.cloudinary.com/dxzw0j1tf/image/upload/v1776853387/logo-19_hb1wsh.jpg', category: 'logo', description: 'Branded thank you card design.' },
  ],

  social: [
    { id: 'social-1',  title: '3 Things You Need to Know',          imageUrl: 'https://res.cloudinary.com/dxzw0j1tf/image/upload/v1776853240/social-1_ctq08a.jpg',  category: 'social', description: 'Educational social post.' },
    { id: 'social-2',  title: 'Ask Us Anything',                    imageUrl: 'https://res.cloudinary.com/dxzw0j1tf/image/upload/v1776853313/social-2_by4qdi.jpg',  category: 'social', description: 'Engagement social media post.' },
    { id: 'social-3',  title: 'Circus',                             imageUrl: 'https://res.cloudinary.com/dxzw0j1tf/image/upload/v1776853221/social-3_zvkgtm.jpg',  category: 'social', description: 'Creative campaign post.' },
    { id: 'social-4',  title: 'Eid Bingo',                         imageUrl: 'https://res.cloudinary.com/dxzw0j1tf/image/upload/v1776853207/social-4_i1uwpd.jpg',  category: 'social', description: 'Festive social media graphic.' },
    { id: 'social-5',  title: 'Happy June',                         imageUrl: 'https://res.cloudinary.com/dxzw0j1tf/image/upload/v1776853226/social-5_mpptkp.jpg',  category: 'social', description: 'Monthly greeting post design.' },
    { id: 'social-6',  title: 'Marketing Trends 01',               imageUrl: 'https://res.cloudinary.com/dxzw0j1tf/image/upload/v1776853187/social-6_d1zbii.jpg',  category: 'social', description: 'Marketing carousel slide.' },
    { id: 'social-7',  title: 'Marketing Trends 02',               imageUrl: 'https://res.cloudinary.com/dxzw0j1tf/image/upload/v1776853196/social-7_fwpygs.jpg',  category: 'social', description: 'Marketing carousel slide.' },
    { id: 'social-8',  title: 'Marketing Trends 03',               imageUrl: 'https://res.cloudinary.com/dxzw0j1tf/image/upload/v1776853188/social-8_vtnvkd.jpg',  category: 'social', description: 'Marketing carousel slide.' },
    { id: 'social-9',  title: 'May New Month',                     imageUrl: 'https://res.cloudinary.com/dxzw0j1tf/image/upload/v1776853195/social-9_v0mcef.jpg',  category: 'social', description: 'Monthly greeting post.' },
    { id: 'social-10', title: 'November',                          imageUrl: 'https://res.cloudinary.com/dxzw0j1tf/image/upload/v1776853209/social-10_nrajba.jpg', category: 'social', description: 'Monthly theme post.' },
    { id: 'social-11', title: 'Ramadan Special',                   imageUrl: 'https://res.cloudinary.com/dxzw0j1tf/image/upload/v1776853221/social-11_k5aijg.jpg', category: 'social', description: 'Special occasion post.' },
    { id: 'social-12', title: 'Unlock More Time',                  imageUrl: 'https://res.cloudinary.com/dxzw0j1tf/image/upload/v1776853195/social-12_kinmv4.jpg', category: 'social', description: 'Productivity tips post.' },
    { id: 'social-13', title: 'Sharp Focus',                       imageUrl: 'https://res.cloudinary.com/dxzw0j1tf/image/upload/v1776853213/social-13_fqupxy.jpg', category: 'social', description: 'Motivational social post.' },
    { id: 'social-14', title: 'Thank You',                         imageUrl: 'https://res.cloudinary.com/dxzw0j1tf/image/upload/v1776853221/social-14_ky9ln7.jpg', category: 'social', description: 'Brand gratitude post.' },
    { id: 'social-15', title: 'Ultimate Solution',                 imageUrl: 'https://res.cloudinary.com/dxzw0j1tf/image/upload/v1776853233/social-15_djo70v.jpg', category: 'social', description: 'Product solution post.' },
    { id: 'social-16', title: 'Your Goal',                         imageUrl: 'https://res.cloudinary.com/dxzw0j1tf/image/upload/v1776853229/social-16_wujhee.jpg', category: 'social', description: 'Motivational goal post.' },
    { id: 'social-17', title: 'Free Graphic Training',             imageUrl: 'https://res.cloudinary.com/dxzw0j1tf/image/upload/v1776853258/social-17_kznfgt.jpg', category: 'social', description: 'Event promotion post.' },
    { id: 'social-18', title: 'Design Campaign',                   imageUrl: 'https://res.cloudinary.com/dxzw0j1tf/image/upload/v1776853220/social-18_xh7fts.jpg', category: 'social', description: 'Creative campaign post.' },
    { id: 'social-19', title: 'First Time Buyer Tip',             imageUrl: 'https://res.cloudinary.com/dxzw0j1tf/image/upload/v1776853253/social-19_eeit9z.jpg', category: 'social', description: 'Real estate tips post.' },
    { id: 'social-20', title: 'Listen to Your Realtor',           imageUrl: 'https://res.cloudinary.com/dxzw0j1tf/image/upload/v1776853257/social-20_lar4ve.jpg', category: 'social', description: 'Real estate advice post.' },
    { id: 'social-21', title: 'Save 30',                          imageUrl: 'https://res.cloudinary.com/dxzw0j1tf/image/upload/v1776853302/social-21_cyeqnp.jpg', category: 'social', description: 'Savings promotion post.' },
    { id: 'social-22', title: 'Effortless',                       imageUrl: 'https://res.cloudinary.com/dxzw0j1tf/image/upload/v1776853296/social-22_pgxouh.jpg', category: 'social', description: 'Lifestyle brand post.' },
    { id: 'social-23', title: 'July New Design',                  imageUrl: 'https://res.cloudinary.com/dxzw0j1tf/image/upload/v1776853237/social-23_raqpyt.jpg', category: 'social', description: 'Monthly design showcase.' },
    { id: 'social-24', title: 'New Concept',                      imageUrl: 'https://res.cloudinary.com/dxzw0j1tf/image/upload/v1776853196/social-24_wfvpeo.jpg', category: 'social', description: 'Brand concept reveal post.' },
    { id: 'social-25', title: 'Make Poster Design',               imageUrl: 'https://res.cloudinary.com/dxzw0j1tf/image/upload/v1776853308/social-25_ykvt8a.jpg', category: 'social', description: 'Design tutorial post.' },
    { id: 'social-26', title: 'Calling',                          imageUrl: 'https://res.cloudinary.com/dxzw0j1tf/image/upload/v1776853197/social-26_govfef.jpg', category: 'social', description: 'Brand awareness post.' },
    { id: 'social-27', title: 'Diffuser Ad Copy',                 imageUrl: 'https://res.cloudinary.com/dxzw0j1tf/image/upload/v1776853198/social-27_mnvlqu.jpg', category: 'social', description: 'Product ad copy design.' },
    { id: 'social-28', title: 'Happy June 2',                     imageUrl: 'https://res.cloudinary.com/dxzw0j1tf/image/upload/v1776853246/social-28_d91of0.jpg', category: 'social', description: 'Seasonal greeting post.' },
    { id: 'social-29', title: 'Struggling Online?',               imageUrl: 'https://res.cloudinary.com/dxzw0j1tf/image/upload/v1776853206/social-29_nevxwx.jpg', category: 'social', description: 'Digital marketing post.' },
    { id: 'social-30', title: 'Running Your Restaurant Blind?',   imageUrl: 'https://res.cloudinary.com/dxzw0j1tf/image/upload/v1776853206/social-30_m8wgr8.jpg', category: 'social', description: 'Restaurant industry post.' },
  ],

  books: [
    { id: 'book-1',  title: 'Crypto Made Easy',                          imageUrl: 'https://res.cloudinary.com/dxzw0j1tf/image/upload/v1776855011/book-1_hgsj4m.jpg',  category: 'book', description: 'Crypto education book cover.' },
    { id: 'book-2',  title: 'Ladies on Assignment – July',               imageUrl: 'https://res.cloudinary.com/dxzw0j1tf/image/upload/v1776854997/book-2_x8k3xm.jpg',  category: 'book', description: 'Monthly magazine journal cover.' },
    { id: 'book-3',  title: 'Ladies on Assignment – March',              imageUrl: 'https://res.cloudinary.com/dxzw0j1tf/image/upload/v1776854982/book-3_neqmoz.jpg',  category: 'book', description: 'Monthly magazine journal cover.' },
    { id: 'book-4',  title: 'Ladies on Assignment – February',           imageUrl: 'https://res.cloudinary.com/dxzw0j1tf/image/upload/v1776855013/book-4_kp948d.jpg',  category: 'book', description: 'Monthly magazine journal cover.' },
    { id: 'book-5',  title: 'Ladies on Assignment – April',              imageUrl: 'https://res.cloudinary.com/dxzw0j1tf/image/upload/v1776854946/book-5_vzrwy7.jpg',  category: 'book', description: 'Monthly magazine journal cover.' },
    { id: 'book-6',  title: 'How Exactly Do I Hear From God?',           imageUrl: 'https://res.cloudinary.com/dxzw0j1tf/image/upload/v1776854966/book-6_wv6z7u.jpg',  category: 'book', description: 'Christian book cover design.' },
    { id: 'book-7',  title: 'Dealing with Condemnation',                 imageUrl: 'https://res.cloudinary.com/dxzw0j1tf/image/upload/v1776854947/book-7_jt2uqh.jpg',  category: 'book', description: 'Spiritual self-help book cover.' },
    { id: 'book-8',  title: 'The Breastplate',                           imageUrl: 'https://res.cloudinary.com/dxzw0j1tf/image/upload/v1776854958/book-8_xj2u3n.jpg',  category: 'book', description: 'Christian manual book cover.' },
    { id: 'book-9',  title: 'Church History Manual',                     imageUrl: 'https://res.cloudinary.com/dxzw0j1tf/image/upload/v1776855002/book-9_tpwwaq.jpg',  category: 'book', description: 'Church education manual cover.' },
    { id: 'book-10', title: 'Faith & Healing Manual',                    imageUrl: 'https://res.cloudinary.com/dxzw0j1tf/image/upload/v1776855077/book-10_zy8wlx.jpg', category: 'book', description: 'Faith teaching manual cover.' },
    { id: 'book-11', title: 'Danger',                                    imageUrl: 'https://res.cloudinary.com/dxzw0j1tf/image/upload/v1776854967/book-11_dixgp5.jpg', category: 'book', description: 'Warning series book cover.' },
    { id: 'book-12', title: 'Speak in Tongues',                          imageUrl: 'https://res.cloudinary.com/dxzw0j1tf/image/upload/v1776854954/book-12_mnw8ix.jpg', category: 'book', description: 'Spiritual gifts book cover.' },
    { id: 'book-13', title: 'Feed What Feeds You',                       imageUrl: 'https://res.cloudinary.com/dxzw0j1tf/image/upload/v1776855024/book-13_nhwlqx.jpg', category: 'book', description: 'Motivational book cover.' },
    { id: 'book-14', title: 'Daily Bread',                               imageUrl: 'https://res.cloudinary.com/dxzw0j1tf/image/upload/v1776854967/book-14_mixn7o.jpg', category: 'book', description: 'Devotional journal cover.' },
    { id: 'book-15', title: 'Loving Me',                                 imageUrl: 'https://res.cloudinary.com/dxzw0j1tf/image/upload/v1776854944/book-15_adfqq7.jpg', category: 'book', description: 'Self-love book cover.' },
    { id: 'book-16', title: 'Love Sense',                                imageUrl: 'https://res.cloudinary.com/dxzw0j1tf/image/upload/v1776854983/book-16_geulgk.jpg', category: 'book', description: 'Relationship guide book cover.' },
    { id: 'book-17', title: 'Prompt Power of AI – Volume 1',             imageUrl: 'https://res.cloudinary.com/dxzw0j1tf/image/upload/v1776854959/book-17_jarv2p.jpg', category: 'book', description: 'AI guide book cover design.' },
    { id: 'book-18', title: 'Prompt Power of AI – Volume 2',             imageUrl: 'https://res.cloudinary.com/dxzw0j1tf/image/upload/v1776854940/book-18_sxus4b.jpg', category: 'book', description: 'AI guide book cover design.' },
    { id: 'book-19', title: 'Gratitude – The Ultimate Pill for Greatness', imageUrl: 'https://res.cloudinary.com/dxzw0j1tf/image/upload/v1776855050/book-19_mbiwdj.jpg', category: 'book', description: 'Motivational book cover.' },
    { id: 'book-20', title: 'Gratitude in Faith & Adversity',            imageUrl: 'https://res.cloudinary.com/dxzw0j1tf/image/upload/v1776855046/book-20_di41mp.jpg', category: 'book', description: 'Spiritual growth book cover.' },
    { id: 'book-21', title: 'Gratitude in Daily Life',                   imageUrl: 'https://res.cloudinary.com/dxzw0j1tf/image/upload/v1776855069/book-21_ueqzju.jpg', category: 'book', description: 'Self-development book cover.' },
    { id: 'book-22', title: 'Gratitude & Mindset Shift',                 imageUrl: 'https://res.cloudinary.com/dxzw0j1tf/image/upload/v1776855044/book-22_jb2oi7.jpg', category: 'book', description: 'Mindset book cover.' },
    { id: 'book-23', title: 'Leaving a Legacy',                          imageUrl: 'https://res.cloudinary.com/dxzw0j1tf/image/upload/v1776855054/book-23_zsrarl.jpg', category: 'book', description: 'Legacy building book cover.' },
    { id: 'book-24', title: 'Victoria Ishola – Final Cover',             imageUrl: 'https://res.cloudinary.com/dxzw0j1tf/image/upload/v1776854958/book-24_xojs9i.jpg', category: 'book', description: 'Author book cover design.' },
    { id: 'book-25', title: 'A little here, alittle there, how to experience increase the bible way',             imageUrl: 'https://res.cloudinary.com/dxzw0j1tf/image/upload/v1776855071/book-25_uzxnzi.jpg', category: 'book', description: 'Christian living book cover.' },
  ],
};
